### ISSUE TITLE
About the sampling operation

### ISSUE THREAD

**Issue by HzZHoO** [jiangzhengkai/LSTS#1]
Thanks for your work!
I have some questions about the sampling operation. 

- Does every pixel has an individual sampling pattern to learn? 
- And once the training is over, are all the sampling pattern fixed and just used to align the features of the test frames?

Very thanks for your help!

**Comment by jiangzhengkai** [comment]
@HzZHoO 
Thanks for your interest. We try two kinds of sampling strategies, including location sensitive sampling and location insensitive(part of code could be seen in [Mxnet-Operator](https://github.com/jiangzhengkai/Mxnet-Operator)). The later one always performs better. And once training is over, the candidate of sampling locations are fixes, the similarity weight could be different during inference.
