### ISSUE TITLE
关于怎样训练lsts网络的问题

### ISSUE THREAD

**Issue by luoyinTT** [jiangzhengkai/LSTS#7]
作者您好，
根据你的usage操作命令，没有办法进行训练，请问是怎样进行训练呢？

**Comment by jiangzhengkai** [comment]
Please see the usage, you need to compile the Mxnet environment and compile the op!

**Comment by luoyinTT** [comment]
可是usage文件里面train的文件experiments/lsts/lsts_end2end_train_test.py和配置文件experiments/lsts_rfcn/cfgs/lsts_network_uniform.yaml在github项目上没有相同文件名的文件，LSTS/experiments/lsts_rfcn/里面的训练代码是impression_train_test_end2end.py，LSTS/lsts_rfcn/里面的训练代码是lsts_network_train_end2end.py


请问应该运行哪个代码才能训练lsts? 需要的配置文件是LSTS/experiments/lsts_rfcn/cfgs/lsts_uniform.yaml&nbsp;吗？



------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "jiangzhengkai/LSTS"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年2月2日(星期二) 中午11:45
收件人:&nbsp;"jiangzhengkai/LSTS"<LSTS@noreply.github.com&gt;;
抄送:&nbsp;"purplr.er"<675085369@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [jiangzhengkai/LSTS] 关于怎样训练lsts网络的问题 (#7)





 
Please see the usage, you need to compile the Mxnet environment and compile the op!
