### ISSUE TITLE
Issues in reproduction

### ISSUE THREAD

**Issue by AmberElferink** [jiangzhengkai/LSTS#8]
As a master study project we tried to reproduce this paper for 35 hours. Our group and two other groups did not manage to replicate the results, since we could not get the code running after 35 hours. We describe our issues on this blog: https://medium.com/death-of-the-author/death-of-the-author-and-the-authors-responsibility-for-their-codebase-685ad0226931

In there, we give general suggestions to prevent these sorts of issues, but also provide all the errors we came across. I believe it would help others if you could take another look at your readme trying to run on a clean linux environment such as we did in the blog. We believe your paper has great results, and many people would like to use it, but get discouraged due to the issues. We post this in case it may help to either help with the readme, or get others facing similar problems past some of them.

**Comment by jiangzhengkai** [comment]
@AmberElferink Hi, I will update the readme and provide the pre-trained model. Please wait.

**Comment by jiangzhengkai** [comment]
@AmberElferink sorry, I am currently working for one deadline. Once done, I will give the requirements and model weights.  Please note that our code is modified from [DFF](https://github.com/msracver/Deep-Feature-Flow).
